apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    solrsearchservice:
      owner: "gattma"
      repository: "SolrSearchService"
      webhook:
        endpoint: "/push"
        port: "12000"
        method: "POST"
      events:
        - "push"
      webhookSecret:
        name: github-webhook-secret
        key: secret
      insecure: false
      active: true
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    controller: eventsource-controller
    eventsource-name: github
    owner-name: github
  name: github-webhook
spec:
  host: ""
  tls:
    termination: edge
  to:
    kind: ""
    name: github-eventsource-svc
    weight: null
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: solrsearchservice
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-solrsearchservice
      eventSourceName: github
      eventName: solrsearchservice
      filters:
        data:
          - path: body.ref
            type: string
            value:
              - "feature/integrate-argo"
  triggers:
    - template:
        name: log-trigger
        log:
          intervalSeconds: 20