apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: image-build-push
spec:
  templates:
    - name: image-build-push
      inputs:
        parameters:
          - name: tag
          - name: namespace
      metadata:
        labels:
          app: argo
      container:
        image: gcr.io/kaniko-project/executor:latest
        args:
          - --dockerfile=Containerfile
          - --context=/mnt/out/{{ workflow.parameters.reponame }}
          - --destination=image-registry.openshift-image-registry.svc.cluster.local:5000/{{ inputs.parameters.namespace }}/{{ workflow.parameters.reponame }}:{{ inputs.parameters.tag }}
          - --skip-tls-verify
        volumeMounts:
          - name: workspace
            mountPath: /mnt/out/
          - name: dockerconfig
            mountPath: /kaniko/.docker
      volumes:
        - name: dockerconfig
          secret:
            secretName: builder-dockerconfig
            items:
              - key: .dockerconfigjson
                path: config.json