apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: parse-branch-and-namespace
spec:
  templates:
    - name: parse-branch-and-namespace
      metadata:
        labels:
          app: argo
      container:
        image: busybox
        name: busybox
        command: [ sh, -c ]
        args: [ "cd /mnt/out/ && touch branch && echo  {{ workflow.parameters.revision }} | cut -d '/' -f3- | cat > branch" ] #
        volumeMounts:
          - name: workspace
            mountPath: /mnt/out/
          - name: podinfo
            mountPath: /etc/podinfo/
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "namespace"
                fieldRef:
                  fieldPath: metadata.namespace
      outputs:
        parameters:
          - name: branch
            valueFrom:
              path: /mnt/out/branch
          - name: namespace
            valueFrom:
              path: /etc/podinfo/namespace